# Name: Joel Miller/ Austin Wagner
# CPSC 2150
# Project: Final Project
# March 28 2023


default: cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java
	javac cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java
run: cpsc2150/listDec/IShuffleList.class cpsc2150/listDec/ShuffleApp.class cpsc2150/listDec/ShuffleList.class
	java cpsc2150.listDec.ShuffleApp

clean:
	rm -f cpsc2150/listDec/*.class
